# Generated by Django 4.1 on 2023-04-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_catgories_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='catgories',
            name='daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catgories',
            name='weekely',
            field=models.BooleanField(default=False),
        ),
    ]
